language: go

sudo: false

go:
  - 1.3
  - 1.4
  - 1.5
  - tip
  - release

before_install:
  - export GOPATH=$HOME/gopath/src/github.com/lby221/GrandmaSchedulingServices/

install:
  - go build server.go routes.go